AWSTemplateFormatVersion: '2010-09-09'
Description: Build a serverless podcast feeds using your S3 bucket with music and
  Lambda
Parameters:
  MusicBucket:
    Description: Name of an existing S3 bucket with MP3 files. Put the artists tracks
      in separate folders in the root.
    Type: String
Resources:
  lambdapodcast:
    Properties:
      CodeUri: s3://tommcm-streamripper/604f4b2ae09737b7b5e41c172cc08b30
      Description: Build a serverless podcast feeds using your S3 bucket with music
        and Lambda
      Environment:
        Variables:
          s3_bucket:
            Ref: MusicBucket
      Events:
        Cron:
          Properties:
            Schedule: rate(1 hour)
          Type: Schedule
      Handler: mp3.handler
      MemorySize: 128
      Policies:
      - S3CrudPolicy:
          BucketName:
            Ref: MusicBucket
      Runtime: python3.6
      Timeout: 60
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
