AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  MusicBucket:
    Type: String
    Description: Name of an existing S3 bucket with MP3 files. Put the artists tracks
      in separate folders in the root.
Description: Build a serverless podcast feeds using your S3 bucket with music and
  Lambda
Resources:
  lambdapodcast:
    Type: AWS::Serverless::Function
    Properties:
      Handler: mp3.handler
      Runtime: python3.6
      Description: Build a serverless podcast feeds using your S3 bucket with music
        and Lambda
      MemorySize: 128
      Timeout: 300
      CodeUri: s3://tommcm-streamripper/b7aa5421c4f9a2e8b05c7c17eed5bd49
      Environment:
        Variables:
          s3_bucket:
            Ref: MusicBucket
      Events:
        Cron:
          Type: Schedule
          Properties:
            Schedule: rate(1 hour)
      Policies:
      - S3CrudPolicy:
          BucketName:
            Ref: MusicBucket
