version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "streamripper-podcast-generator-v3"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-17k83buigtilx"
s3_prefix = "streamripper-podcast-generator-v3"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "MusicBucket=\"tommcm-streamripper\""
